pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "LeTianPaiRobot"

include ':LeTianPaiLauncher'
include ':CommandLib'
include ':LeTianPaiLauncherBusinessLib'
include ':LeTianPaiLauncherBaseLib'
include ':LeTianPaiExpression'
include ':guideLib'
include ':expression'
include ':library'
include ':displayview'
include ':LetianpaiAudioService'
include ':audio'
include ':message'
include ':player'
include ':GestureFactory'
include ':GeeUINotice'
include ':FmodSound'
