plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

apply from: rootProject.file('gradle/android-sdk.gradle')

android {
    namespace 'com.renhejia.robot.commandlib'

    defaultConfig {
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api libs.androidx.appcompat
    api libs.gson
    testImplementation libs.junit
}
