plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

apply from: rootProject.file('gradle/android-sdk.gradle')

android {
    namespace 'com.demon.fmodsound'

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    api files('libs/fmod.jar')
}
