[versions]
agp = "8.13.0"
kotlin = "2.0.21"
compileSdk = "36"
minSdk = "30"
targetSdk = "36"
coreKtx = "1.15.0"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
recyclerview = "1.3.2"
viewpager = "1.1.0"
annotation = "1.9.1"
localbroadcastmanager = "1.1.0"
gson = "2.11.0"
okhttp = "4.12.0"
okio = "3.9.1"
media3 = "1.5.1"
ijkplayer = "0.8.8"
glide = "4.16.0"
lottie = "6.6.2"
picasso = "2.8"
xlog = "1.10.1"
zxing = "3.5.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-viewpager = { group = "androidx.viewpager", name = "viewpager", version.ref = "viewpager" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
ijkplayer-java = { group = "tv.danmaku.ijk.media", name = "ijkplayer-java", version.ref = "ijkplayer" }
ijkplayer-arm64 = { group = "tv.danmaku.ijk.media", name = "ijkplayer-arm64", version.ref = "ijkplayer" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
