plugins {
    alias(libs.plugins.android.library)
}

apply from: rootProject.file('gradle/android-sdk.gradle')

android {
    namespace 'com.letianpai.robot.notice'

    defaultConfig {
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api libs.gson
    implementation libs.bundles.okhttp
}
