plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

apply from: rootProject.file('gradle/android-sdk.gradle')

android {
    namespace 'com.renhejia.robot.launcher'

    defaultConfig {
        applicationId "com.renhejia.robot.launcher"
        versionCode 202405162
        versionName "1.1." + versionCode
    }

    def keystoreFile = file('../keystore/letianpai.jks')
    signingConfigs {
        config {
            if (keystoreFile.exists()) {
                storeFile keystoreFile
                keyAlias 'letianpai'
                keyPassword findProperty('LETIANPAI_KEY_PASSWORD') ?: ''
                storePassword findProperty('LETIANPAI_STORE_PASSWORD') ?: ''
            }
        }
    }

    buildTypes {
        debug {
            if (keystoreFile.exists()) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        release {
            if (keystoreFile.exists()) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        baseline = file("lint-baseline.xml")
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.viewpager
    implementation libs.androidx.localbroadcastmanager
    implementation libs.androidx.annotation
    api project(':LeTianPaiLauncherBusinessLib')
    api project(':CommandLib')
    api project(':GestureFactory')
    api project(':guideLib')
    api project(':expression')
    api project(':displayview')
    api project(':GeeUINotice')
    implementation libs.bundles.okhttp
}
