plugins {
    id 'com.android.application'
}

android {
    namespace 'com.letianpai.robot.mcuservice'
    compileSdk 36

    defaultConfig {
        applicationId "com.letianpai.robot.mcuservice"
        minSdk 30
        targetSdk 36
        versionCode 3
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {

        config {
            storeFile file('../keystore/letianpai.jks')
            keyAlias 'letianpai'
            keyPassword 'letianpai0801'
            storePassword 'letianpai0801'
        }

    }

    buildTypes {
        debug {
            signingConfig signingConfigs.config
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        release {
            signingConfig signingConfigs.config
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
//
//    implementation 'androidx.appcompat:appcompat:1.7.0'
//    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
//    testImplementation 'junit:junit:4.13.2'
//    androidTestImplementation 'com.android.support.test:runner:1.0.2'
//    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':library')
    implementation project(':CommandLib')
    api 'com.google.code.gson:gson:2.11.0'
}