plugins {
    alias(libs.plugins.android.application)
}

apply from: rootProject.file('gradle/android-sdk.gradle')

android {
    namespace 'com.letianpai.robot.audioservice'

    defaultConfig {
        applicationId "com.letianpai.robot.audioservice"
        versionCode 2401181
        versionName "1.1." + versionCode
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    def keystoreFile = file('../keystore/letianpai.jks')
    signingConfigs {
        config {
            if (keystoreFile.exists()) {
                storeFile keystoreFile
                keyAlias 'letianpai'
                keyPassword findProperty('LETIANPAI_KEY_PASSWORD') ?: ''
                storePassword findProperty('LETIANPAI_STORE_PASSWORD') ?: ''
            }
        }
    }

    buildTypes {
        debug {
            if (keystoreFile.exists()) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            if (keystoreFile.exists()) {
                signingConfig signingConfigs.config
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        aidl true
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.gson
    implementation libs.bundles.okhttp
    api project(':CommandLib')
}
